FROM ubuntu:20.04
LABEL description = "Api Rest"
RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
RUN apt-get install sqlite3 -y

ENV requirements /home/requirements.txt
COPY requirements.txt ${requirements}

RUN pip3 install pytest==7.1.1
RUN pip3 install uvicorn==0.17.6
RUN pip3 install fastapi==0.78.0
RUN pip3 install python-multipart==0.0.5

WORKDIR /home/